server:
  port: 8081

spring:
  application:
    name: add-song
  datasource:
    url: jdbc:h2:mem:mp
    driverClassName: org.h2.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS


