server:
  port: 8099

play-song:
  ribbon:
    eureka:
      enabled: true
    listOfServers: http://localhost:8085,http://localhost:8095
    ServerListRefreshInterval: 15000

spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web
eureka:
  client:
    instance:
      hostname: localhost
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/},${EUREKA_URL:http://localhost:8762/eureka/}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000

zuul:
  routes:
    play-service:
      path: /**
      serviceId: play-song
    delete-service:
      path: /**
      serviceId: delete-song

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
