server:
  port: 8088

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:user
    driverClassName: org.h2.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
