spring:
  application:
    name: discovery-service
---
spring:
  profiles: peer1

eureka:
  instance:
    metadataMap:
      zone: zone1
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    preferSameZoneEureka: true
    healthCheck:
        enabled: true
    serviceUrl:
#      defaultZone: ${EUREKA_URL:http://${eureka.instance.hostname}:${server.port}/eureka/}
       defaultZone: ${EUREKA_URL:http://peer2/eureka/}

server:
  port: ${PORT:8761}
---
spring:
  profiles: peer2

eureka:
  instance:
    metadataMap:
      zone: zone2
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    preferSameZoneEureka: true
    healthCheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://peer1/eureka/}

server:
  port: ${PORT:8762}


