spring:
  application:
    name: play-song
  rabbitmq:
    host: localhost
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web

#http://localhost:{8084 or 8094}/actuator/hystrix.stream
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
---
spring:
  profiles: peer1
eureka:
  instance:
    metadata-map:
      zone: zone1
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/},${EUREKA_URL:http://localhost:8762/eureka/}
server:
  port: ${PORT:8084}
---
spring:
  profiles: peer2
eureka:
  instance:
    metadata-map:
      zone: zone2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/},${EUREKA_URL:http://localhost:8762/eureka/}
server:
  port: ${PORT:8094}

